alasdecristal/urls.py
from django.conf.urls import include
from django.conf.urls import url

from alasdecristal.views import AboutView
from alasdecristal.views import AgendaView
from alasdecristal.views import HomeView
from alasdecristal.views import ProductsView

from ecommerce.views import ContactCreate
from ecommerce.views import ContactThanks
from ecommerce.views import NewsletterSubscriptionCreate
from ecommerce.views import QuoteCreate

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Static pages
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^products/$', ProductsView.as_view(), name='products'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^agenda/$', AgendaView.as_view(), name='agenda'),

    # Ecommerce views
    url(r'^contact/$', ContactCreate.as_view(), name='contact'),
    url(r'^ecommerce/subscription/add/$',
        NewsletterSubscriptionCreate.as_view(), name='subscription-add'),
    url(r'^ecommerce/contact/thanks/$',
        ContactThanks.as_view(), name='contact-thanks'),
    url(r'^ecommerce/quote/add/$',
        QuoteCreate.as_view(), name='quote-add'),
]

apps/ecommerce/models.py
from django.utils.translation import ugettext as _

from django.db import models


class Team(models.Model):
    class Meta:
        verbose_name = _('Team')
        verbose_name_plural = _('Teams')

    def __str__(self):
        return '%s' % self.name

    name = models.CharField(max_length=250, verbose_name='Nombre')


class TeamMember(models.Model):
    class Meta:
        verbose_name = _('Miembro del Equipo')
        verbose_name_plural = _('Miembros del Equipo')

    def __str__(self):
        return '%s' % self.name

    team = models.ForeignKey(Team)
    name = models.CharField(max_length=250, verbose_name='Nombre')
    bio = models.TextField()
    image = models.ImageField(upload_to='team/images')


class Product(models.Model):

    class Meta:
        verbose_name = _('Producto')
        verbose_name_plural = _('Productos')

    def __str__(self):
        return '%s' % self.name

    id = models.SlugField(unique=True, primary_key=True)
    name = models.CharField(max_length=250, verbose_name='Nombre')
    short_description = models.TextField(verbose_name='Descirpción')
    thumbnail = models.ImageField(
        upload_to='products/thumbnails',
        verbose_name='Icono'
    )
    featured = models.BooleanField(
        verbose_name='En promoción, el que lleve, el que escoja'
    )


class ProductImage(models.Model):

    class Meta:
        verbose_name = _('ProductImage')
        verbose_name_plural = _('ProductImages')

    def __str__(self):
        return '%s' % self.title

    product = models.ForeignKey(Product)
    image = models.ImageField(
        upload_to='products/images',
        verbose_name='Imagen'
    )
    title = models.CharField(max_length=250, verbose_name='Título')
    description = models.TextField(verbose_name='Descirpción')
    caption_on = models.BooleanField(verbose_name='Activar caption')


class HintGroup(models.Model):

    class Meta:
        verbose_name = _('Grupo de recomendaciones')
        verbose_name_plural = _('Grupos de recomendaciones')

    def __str__(self):
        return self.title

    title = models.CharField(max_length=250)


class Hint(models.Model):
    class Meta:
        verbose_name = _('Recomendación')
        verbose_name_plural = _('Recomendacións')

    def __str__(self):
        return self.text

    hint_group = models.ForeignKey(HintGroup)
    text = models.TextField()


class NewsletterSubscription(models.Model):
    class Meta:
        verbose_name = _('Suscripción al Newsletter')
        verbose_name_plural = _('Suscripciónes al Newsletter')

    def __str__(self):
        return '%s' % self.email

    date = models.DateTimeField(auto_now_add=True, verbose_name='Fecha')
    name = models.CharField(max_length=250, verbose_name='Nombre')
    email = models.EmailField(
        verbose_name='Email',
        unique=True)


class Contact(models.Model):
    class Meta:
        verbose_name = _('Contacto')
        verbose_name_plural = _('Contactos')

    def __str__(self):
        return '%s' % self.subject

    date = models.DateTimeField(auto_now_add=True, verbose_name='Fecha')
    name = models.CharField(max_length=250, verbose_name='Nombre')
    subject = models.CharField(max_length=250, verbose_name='Asunto')
    email = models.EmailField(verbose_name='Email')
    phone = models.CharField(blank=True, null=True,
                             max_length=250, verbose_name='Teléfono')
    city = models.CharField(blank=True, null=True,
                            max_length=250, verbose_name='Ciudad')
    message = models.TextField(verbose_name='Mensaje')


class Quote(models.Model):
    class Meta:
        verbose_name = _('Cotización')
        verbose_name_plural = _('Cotizaciónes')

    def __str__(self):
        return '%s' % self.name

    date = models.DateTimeField(auto_now_add=True, verbose_name='Fecha')
    name = models.CharField(max_length=250, verbose_name='Nombre')
    subject = models.CharField(max_length=250, verbose_name='Asunto')
    email = models.EmailField(verbose_name='Email')
    phone = models.CharField(blank=True, null=True,
                             max_length=250, verbose_name='Teléfono')
    city = models.CharField(blank=True, null=True,
                            max_length=250, verbose_name='Ciudad')


class QuoteLine(models.Model):

    class Meta:
        verbose_name = _('QuoteLine')
        verbose_name_plural = _('QuoteLines')

    def __str__(self):
        return '%s' % self.product

    quote = models.ForeignKey(Quote)
    product = models.CharField(max_length=250, verbose_name='Producto')
    quantity = models.IntegerField(verbose_name='Cantidad')

files/templates/about.html
{% extends "base.html" %}

{% block title %}
    Acerca de | Fundación Alas de Cristal.
{% endblock title %}

{% block description %}
    Equipo de trabajo de la Fundación Alas de Cristal.
{% endblock description %}

{% block content %}
    <section id="about">
        <p class="lead">
            La <strong>Fundación Alas de Cristal</strong> surge en el año 2008 con la promoción, gestión y ejecución de propuestas, proyectos y productos que contribuyen a acercar a la población en temas que aporten a la construcción de una ciudad, un país y un mundo con mayor compromiso hacia la humanidad y sensibilidad con el planeta. Por eso elegimos el arte, la educación y el medio ambiente.

        </p>
        <h2>Institucional</h2>
        <h3>Trayectoria</h3>
        <p>Ya cumplimos 5 años de emprendimiento educativo, cultural, científico y artístico. Hemos crecido, hemos desarrollado nuevos productos y estamos en innovación permanente.</p>

        <h3>Labor Social</h3>
        <p>La Fundación Alas de Cristal contribuye al bienestar social, entre otras, dando ayudas, estímulos o becas a jóvenes talentos, o donación y dotación de material lúdico cultural para establecimientos educativos, en lo cual destinará un porcentaje de sus ingresos.</p>

        <h3>Misión</h3>
        <p>Exaltar la vida por medio del arte y ofrecer educación, buscando mantener un equilibrio entre el ser humano y el medio ambiente.</p>

        <h3>Visión</h3>
        <p>Una Humanidad en paz y un planeta para la vida.</p>

        <h3>Nuestro lema</h3>
        <p>Por la Elevación de la Vida.</p>
    </section>

    <section id="team">
        <h2>Nuestro equipo</h2>
        
        {% for team in teams %}
            {% include "snipets/team.html" %}
        {% endfor %}

    </section>

{% endblock content %}

files/templates/agenda.html
{% extends "base.html" %}

{% block title %}
    Agenda ambiental | Fundación Alas de cristal.
{% endblock title %}

{% block decription %}
    Agenda ambiental propuesta por la Fundación Alas de cristal.
{% endblock decription %}


{% block extra_head %}
    
{% endblock extra_head %}

{% block content %}
    <section id="agenda">
        <h2>Nuestra Agenda Ambiental</h2>
        <ol>
            <li>Ahorrar energía en casa. </li>
            <li>Ahorrar agua en casa.</li>
            <li>Aprender a reciclar.</li>
            <li>Ahorrar papel.</li>
            <li>Limitar el uso de plásticos.</li>
            <li>Usar envases biodegradables</li>
            <li>Limitar el uso de químicos en casa.</li>
            <li>Usar el carro racionalmente.</li>
            <li>Proteger la biodiversidad</li>
            <li>Pensar global y actuar local.</li>
        </ol>
    </section>

    <section id="recycle">
        <h2>Aprender a reciclar</h2>
        <p>La manera más fácil de aprender a reciclar es con la norma de   las tres R: Reducir, Reutilizar, Reciclar.</p> 

        <h3>Reduzcamos</h3>
        <ul>
            <li>Reducimos cuando consumimos racionalmente y evitamos el derroche:</li>
            <li>Elijamos los productos con menos envoltorios. </li>
            <li>Llevemos al mercado una bolsa reutilizable o el carrito.</li>
            <li>Limitemos el consumo de productos de usar y tirar. </li>
        </ul>

        <h3>Reutilicemos</h3>
        <ul>
            <li>Reutilizar consiste en darle la máxima utilidad a las cosas.</li>
            <li>Compremos líquidos en botellas de vidrio retornables </li>
            <li>Utilicemos el papel por las dos caras </li>
            <li>Regalemos la ropa que no usamos </li>
        </ul>

        <h3>Reciclemos</h3>
        <ul>
            <li>Reciclar consiste en usar los materiales una y otra vez. Separemos en casa:</li>
            <li>Materia orgánica (restos de comidas). </li>
            <li>Papel, cartón, vidrio, metales, plástico.</li>
        </ul>
    </section>

    <section id="hints">
        <h2>Recomendaciones para...</h2>
        {% include "snipets/hints.html" %}
    </section>
{% endblock content %}

files/templates/base.html
{% load staticfiles %}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %} Fundación alas de cristal {% endblock title %}</title>
        <meta name="description" content="{% block description %}{% endblock description %}">
        <meta name="viewport" content="width=device-width">
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
        {% block extra_head %}{% endblock extra_head %}
    </head>
    <body>
        <!--[if lt IE 10]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->


        <div class="container">
        <header>
            <div id="header-inner">
                <div id="logo">
                    <a href="/">
                        <img src="{% static 'images/elements/logo.png' %}" alt="Alas de cristal">
                    </a>
                </div>
                <nav>
                    <div class="navitem"><a href="{% url 'products' %}">Productos</a></div>
                    <div class="navitem"><a href="{% url 'about' %}">Nosotros</a></div>
                    <div class="navitem"><a href="{% url 'agenda' %}">Agenda Ambiental</a></div>
                    <div class="navitem"><a href="{% url 'contact' %}">Contacto</a></div>
                </nav>
            </div>
        </header>

        <div class="content">

        {% block content %}

        {% endblock content %}

        </div>

        <footer>
            <div id="footer-inner">
                <div id="footer-contact">
                    <h2>Newsletter</h2>
                    <form class="ajax-form" role="form" data-source="{% url 'subscription-add' %}" action="{% url 'subscription-add' %}"  data-success="{% url 'contact-thanks' %}" >
                    </form>
                </div>

                <div id="footer-info">
                    <div id="footer-social">
                        <div class="fb-like" data-href="https://www.facebook.com/pages/Alas-de-Cristal/194620507235240" data-width="450" data-layout="button_count" data-show-faces="true" data-send="false"></div>
                        <div id="fb-root" style="display: inline-block"></div>
                        <script>(function(d, s, id) {
                          var js, fjs = d.getElementsByTagName(s)[0];
                          if (d.getElementById(id)) return;
                          js = d.createElement(s); js.id = id;
                          js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
                          fjs.parentNode.insertBefore(js, fjs);
                        }(document, 'script', 'facebook-jssdk'));</script>

                        <a href="https://twitter.com/F_AlasdeCristal" class="twitter-follow-button" data-show-count="false" data-lang="es" data-show-screen-name="false">Seguir a @F_AlasdeCristal</a>
                        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </div>
                    <div id="alas-values">
                        Arte <span class="blue">/</span> Educación <span class="pink">/</span> Medio Ambiente
                    </div>
                    <div id="alas-email">
                        <a href="mailto:fundacion@alasdecristal.org">fundacion@alasdecristal.org</a>
                    </div>
                    <div id="alas-city">
                        Bogotá - Colombia
                    </div>
                    <div id="alas-copy">
                        <span class="copy-symbol">&copy;</span> 2013-2016
                    </div>
                </div>
            </div>
        </footer>
        </div>


        <script src="{% static 'scripts/vendor.js' %}"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-37679871-4', 'alasdecristal.org');
          ga('send', 'pageview');

        </script>

        <script data-main="{% static 'scripts/main' %}" src="{% static 'bower_components/requirejs/require.js' %}"></script>
</body>
</html>

files/templates/contact.html
{% extends "base.html" %}

{% block title %}
    Contacto | Fundación Alas de Cristal
{% endblock title %}

{% block description %}
    Información de contacto de la Fundación Alas de Cristal
{% endblock description %}

{% block extra_head %}
    
{% endblock extra_head %}

{% block content %}
    
    <p class="lead">
        Si lo prefieres puedes solicitar una <a href="{% url 'quote-add' %}"> cotización </a>.
    </p>

    <div class="row">
        <div class="form-wrapper">
            <div id="contact-form">
                <h2>CONTÁCTENOS</h2>
                <form role="form" action="{% url 'contact' %}" method="POST">

                {% csrf_token %}

                <div class="form-group {% if form.name.errors %} has-error {% endif %}">
                    <label for="id_name">Nombre</label>
                    <input id="id_name" maxlength="250" name="name" type="text" class="form-control" placeholder="John Snow" required>
                </div>

                <div class="form-group {% if form.subject.errors %} has-error {% endif %}">
                    <label for="id_subject">Asunto</label>
                    <input id="id_subject" maxlength="250" name="subject" type="text" class="form-control" placeholder="Asunto" required>
                </div>

                <div class="form-group {% if form.email.errors %} has-error {% endif %}">
                    <label for="id_email">Email</label>
                    <input id="id_email" maxlength="75" name="email" type="email" class="form-control" placeholder="you@mail.com"  required>
                </div>

                <div class="form-group {% if form.phone.errors %} has-error {% endif %}">
                    <label for="id_phone">Teléfono</label>
                    <input id="id_phone" maxlength="250" name="phone" type="text" class="form-control" placeholder="(opcional)">
                </div>

                <div class="form-group {% if form.city.errors %} has-error {% endif %}">
                    <label for="id_city">Ciudad</label>
                    <input id="id_city" maxlength="250" name="city" type="text" class="form-control" placeholder="(opcional)">
                </div>

                <div class="form-group {% if form.message.errors %} has-error {% endif %}">
                    <label for="id_message">Mensaje</label>
                    <textarea cols="40" id="id_message" name="message" rows="10" class="form-control" placeholder="Mensaje" required></textarea>
                </div>


                <button type="submit" class="btn btn-pink">ENVIAR</button>

                </form>
            </div>
        </div>

    </div>

    <section id="contact-info">
        <div class="row">
            <article id="info-bogota" class="col-sm-6">
                <h2 class="name"><span class="blue">Fundación Alas de Cristal</span> <br> <small style="font-size: 22px;" class="pink">Bogotá - Colombia</small></h2>
                <div class="addres" style="font-size:16px; line-height: 22px;"><strong class="muted">Cr 16 # 32 – 83</strong> </div>
                <div class="phone" style="font-size:16px; line-height: 22px;"><strong class="muted">(57)(1) 2 85 85 60</strong></div>
                <h3><strong class="pink">Contacto</strong></h3>
                <a style="font-family: yanone; font-size:18px;" href="mailto:fundacion@alasdecristal.org">fundacion@alasdecristal.org</a>
                <h3><strong class="pink">Dirección General</strong></h3>
                <a style="font-family: yanone; font-size:18px;" href="mailto:direccion@alasdecristal.org">direccion@alasdecristal.org</a>
            </article>
            <article id="info-us" class="col-sm-6">
                <h2 class="name"><span class="blue">Fundación Alas de Cristal</span> <br> <small style="font-size: 22px;" class="pink">Tampa, FL - Estados Unidos</small></h2>
                <div class="addres" style="font-size:16px; line-height: 22px;"><strong class="muted">6211 Savannah Breeze Ct.</strong></div>
                <div class="phone" style="font-size:16px; line-height: 22px;"><strong class="muted">(813) 382 7416</strong> </div>
                <h3><strong class="pink">Contacto</strong></h3>
                <a style="font-family: yanone; font-size:18px;" href="mailto:fundacionalasdecristal@alasdecristal.org">fundacionalasdecristal@alasdecristal.org</a>
            </article>
        </div>
    </section>
{% endblock content %}

files/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    Fundación Alas de Cristal
{% endblock title %}

{% block description %}
    La Fundación Alas de Cristal surge en el año 2008 y de dedica a la promoción, gestión y ejecución de proyectos para sensibilizar a la población en temas como la humanidad y el planeta. Por eso elegimos el arte, la educación y el medio ambiente.
{% endblock description %}

{% block extra_head %}{% endblock extra_head %}

{% block content %}
    <section id="hero">
        <p class="lead" style="text-align: center; font-face: yanone;">
            Ante la amenaza del cambio climático, la Fundación Alas de Cristal desarrolla proyectos que difundan la belleza y riqueza de nuestra biodiversidad e invitar a su defensa y protección como el ejercicio de una nueva ciudadanía ambiental.
            <br>
            ¡Te invitamos a conocer nuestros productos y servicios!
        </p>
    </section>

    <section id="almanac">

        <div class="almanac-logo" style="text-align: center;">
            <a href="{% url 'products' %}">
                <img style="margin: 0 auto;" src="{% static 'images/almanac/logo.png' %}" alt="Almanaque">
            </a>
        </div>

    </section>
{% endblock content %}

files/templates/products.html
{% extends "base.html" %}

{% block title %}
    Prouctos | Fundación Alas de Cristal
{% endblock title %}

{% block description %}
    Productos y proyectos realizados por la Fundación Alas de Cristal.
{% endblock description %}

{% block extra_head %}{% endblock extra_head %}

{% block content %}
    <section id="pithch">
        <p class="lead">Nuestros productos son material educativo, cultural, científico y artístico; son exclusivos y originales, elaborados por especialistas, con el aval del Instituto Alexander von Humboldt; son de gran impacto, alta recordación, alta penetración y bajo costo, y son excelentes para promocionar y fortalecer la imagen empresarial e institucional.</p>
    </section>

    <section id="what">
        <h3>Lo que hacemos</h3>
        <p>
            Diseñamos y desarrollamos productos editoriales, impresos* y digitales, tales como: mapas, álbumes, manuales, libros y afiches para apoyar campañas de sensibilización en temas de Arte, Educación y Medio Ambiente.
        </p>
                
        <h3>Vincúlese</h3>
        <p>
            La vinculación por parte de su empresa a este tipo de campañas contribuye a la construcción de imagen. La promoción de nuestros productos educativos aporta a la gestión de Responsabilidad Social Empresarial.
        </p>
        
        <h3>Lo que ofrecemos</h3>
        <p>
            Adquiera nuestros exclusivos productos que llevarán su logotipo institucional.
        </p>

        <small>*Todos nuestros productos impresos, están hechos con papel y tintas ecológicos.</small>

    </section>

    <style>
        .thumbnail {
            background-color: transparent;
        }
    </style>

    <section id="featured">
        <h2>Nuevos productos</h2>
        {% for bucket in featured %}
            <div class="row">
                {% for product in bucket %}
                    {% include "snipets/product.html" %}                    
                {% endfor %}
            </div>
        {% endfor %}
    </section>


    <section id="products">
        <h2>Proyectos realizados</h2>
        {% for bucket in products %}
            <div class="row">
                {% for product in bucket %}
                    {% include "snipets/product.html" %}                    
                {% endfor %}
            </div>
        {% endfor %}
    </section>

    <section id="product-traits">
        <h2>Caracterísiticas de nuestros productos</h2>
        <ul>
            <li>Tenemos un propósito educativo y buscamos desarrollar productos didácticos, instructivos y pedagógicos para la población en general. De manera especial, nos interesan los niños.</li>
            <li>Tenemos una intención ecológica y ambiental, y una invitación a la defensa, protección y conservación de las especies.</li>
            <li>Buscamos desarrollar nuestros productos con un alto criterio  artístico.</li>
            <li>Para nosotros es primordial contar con especialistas que avalen todo nuestro contenido informativo e investigativo.</li>
        </ul>
    </section>
{% endblock content %}